"""Initial migration

Revision ID: 839699612e6b
Revises: 
Create Date: 2024-10-26 16:01:20.870207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '839699612e6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('contact_person', sa.String(length=50), nullable=False),
    sa.Column('contact_email', sa.String(length=50), nullable=False),
    sa.Column('contact_phone', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terminals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('gps_latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('gps_longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('comissioning_date', sa.Date(), nullable=False),
    sa.Column('customer_company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_company_id'], ['customer_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('customer_company')
    op.drop_index('email', table_name='user')
    op.drop_table('user')
    op.drop_table('terminal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terminal',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('gps_latitude', mysql.DECIMAL(precision=9, scale=6), nullable=False),
    sa.Column('gps_longitude', mysql.DECIMAL(precision=9, scale=6), nullable=False),
    sa.Column('manufacturer', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('comissioning_date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'user', ['email'], unique=True)
    op.create_table('customer_company',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('contact_person', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('contact_email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('contact_phone', mysql.VARCHAR(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('terminals')
    op.drop_table('customer_companies')
    # ### end Alembic commands ###
