from my_project.terminals.domain.terminal import Terminal
from my_project.terminals.domain.customer_comp import CustomerCompany
from my_project.terminals.domain.invoices import Invoice
from my_project.terminals.domain.maintenance_types import MaintenanceType
from my_project.terminals.domain.payments import Payment
from my_project.terminals.domain.service_order_parts import ServiceOrderPart
from my_project.terminals.domain.service_orders import ServiceOrder
from my_project.terminals.domain.service_parts import ServicePart
from my_project.terminals.domain.technician_maintenance import TechnicianMaintenance
from my_project.terminals.domain.technicians import Technician
from my_project.terminals.domain.customer_comp import CustomerCompany
from my_project.terminals.dao.orders.terminal_dao import TerminalDAO
from my_project.terminals.dao.orders.customer_comp_dao import CustomerCompanyDAO
from my_project.terminals.dao.orders.technicians_dao import TechnicianDAO
from my_project.terminals.dao.orders.invoices_dao import InvoiceDAO
from my_project.terminals.dao.orders.maintenance_types_dao import MaintenanceTypeDAO
from my_project.terminals.dao.orders.payments_dao import PaymentDAO
from my_project.terminals.dao.orders.service_order_parts_dao import ServiceOrderPartDAO
from my_project.terminals.dao.orders.service_orders_dao import ServiceOrderDAO
from my_project.terminals.dao.orders.service_parts_dao import ServicePartDAO
from my_project.terminals.dao.orders.technician_maintenance_dao import TechnicianMaintenanceDAO

