from my_project.terminals.domain.customer_comp import CustomerCompany
from my_project.terminals.domain.terminal import Terminal
from my_project.terminals.domain.invoices import Invoice
from my_project.terminals.domain.maintenance_types import MaintenanceType
from my_project.terminals.domain.payments import Payment
from my_project.terminals.domain.service_order_parts import ServiceOrderPart
from my_project.terminals.domain.service_orders import ServiceOrder
from my_project.terminals.domain.service_parts import ServicePart
from my_project.terminals.domain.technician_maintenance import TechnicianMaintenance
from my_project.terminals.domain.technicians import Technician