name: Deploy Flask App to EC2
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SHH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
            cd /home/ubuntu/lab-4-databases/app
            git pull origin main
            cd app
            source venv/bin/activate
            cd lab-4-databases/app
            pip install -r requirements.txt
            pip install werkzeug==2.3.7
            pip install --upgrade flask sqlalchemy flask-sqlalchemy alembic
            sudo systemctl restart lab1
          EOF
